### PR TITLE
Add readme from src folder to summary

### PR DESCRIPTION
**Pull request by sbatial**
This pr will do 2 things:
- add the readme file from src folder to the summary (if one exists)
- rebase to the newest mdbook version

## Rebase

I wasn't sure if this should be a standalone pr but because no code needed to be changed I decided that I would put it together into one.
The only 'problem' was git not fully understanding the merge.
It was confused by the addition of `let summary ...` (Lines 16-35) and

```rust
        if cfg.create_missing {
            create_missing(&src_dir, &summary)
                .with_context(|| "Unable to create missing chapters")?;
        }
```

having a different intendation/formatting. (Lines 27-30)

## Readme file

As discussed in [mdbook#1588](https://github.com/rust-lang/mdBook/pull/1588) if a `readme.md` exists in the `src` folder of the book it won't be included in the summary.
That's because the `include_path` function sorts out all paths ending with a `README.md` or a `summary.md` and is fed with the `src` of the book and all it's subfolders/~files.
So all paths lower than `src` are actually included and if they contain a `README.md` it will be added.
But because `src` itself never is included the `./src/README.md` will be excluded and never added.

This pr will check if a `README.md` exists and if so add it as a "preface" chapter to the summary.

### CODE REVIEW

**Comment by sbatial** [comment]
I hope this is helpful.
I'm not sure if it makes more sense to open a dedicated pr for the rebase so all the changes will have the correct author.

**Comment by timothee-haudebourg** [comment]
Ah! I just saw your PR, just after doing the changes by myself... sorry. I don't know why I haven't been notified. GitHub seems to not notify you of PRs and issues on your own repos unless you are specifically @ mentioned.

I tried to check if we did the same change regarding the `src/README.md` file, but I can't find what you changed (there is too much noise with the rebase). However I think you were right to do a rebase where I just merged the branches. I'll fix that on my side.

**Comment by timothee-haudebourg** [comment]
After checking I know understand that you don't automatically watch forks as any other new repo. That's why I haven't been notified.

**Comment by sbatial** [comment]
Ok great 👍 
I checked and it seems as if I hadn't pushed my changes yet.
Thank you very much for your work on this 🙏

**Pull request closed without merging**
